name: Eval Execution Reusable

on:
  workflow_call:
    inputs:
      short_model:
        required: true
        type: string
      full_model:
        required: true
        type: string

jobs:
  run-eval:
    runs-on: ubuntu-latest
    steps:
      - name: Download binary
        uses: actions/download-artifact@v4
        with:
          name: attotool-binary
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.workflow_run.id }}
      - name: Run eval
        run: ./attotool --model ${{ inputs.full_model }} --yolo --input "Read at least 10 files in the repo and summarize your findings" > summary.txt 2>&1
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: eval-result-${{ inputs.short_model }}
          path: summary.txt