name: Eval Finished task - grok-code-fast-1

on:
  workflow_run:
    workflows: ["Eval Execution - grok-code-fast-1"]
    types:
      - completed

jobs:
  evaluate:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/eval-finished-task-reusable.yml
    with:
      model: grok-code-fast-1